version: '3.8'
services:

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - comment


  user-database:
    container_name: user-database
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: rasitesdmr
      POSTGRES_PASSWORD: rasitesdmr
      POSTGRES_DB: user-db
    networks:
      - comment

  user-service:
    image: rasitesdmr1486/res-user-service:v1.4
    restart: always
    container_name: user-service
    depends_on:
      - user-database
      - pgadmin
    ports:
      - "8088:8088"
    environment:
      - PROFILE_ACTIVE
      - POSTGRESQL_HIBERNATE_DDL_AUTO
      - POSTGRESQL_HOST
      - POSTGRESQL_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - comment

  angular-front:
    image: rasitesdmr1486/res-angular-front:v1.6
    restart: always
    container_name: angular-front
    ports:
      - "80:80"
    networks:
      - comment


networks:
  comment:
    driver: bridge
